version: '3.8'

services:
  puppeteer:
    build: ./puppeteer
    container_name: puppeteer-api
    ports:
      - "3000:3000"
    env_file:
      - ./puppeteer/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped