[supervisord]
nodaemon=true

[program:squid]
command=/usr/sbin/squid -N
autostart=true
autorestart=true

[program:xrdp-sesman]
command=/usr/sbin/xrdp-sesman
autostart=true
autorestart=true

[program:xrdp]
command=/usr/sbin/xrdp -nodaemon
autostart=true
autorestart=true
